# Generated by Django 2.0.4 on 2018-05-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='Nome', max_length=50)),
            ],
            options={
                'db_table': 'Curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='Nome', max_length=60)),
                ('data', models.DateField(db_column='Data')),
                ('status', models.CharField(db_column='Status', max_length=8)),
                ('planodeensino', models.CharField(db_column='PlanoDeEnsino', max_length=2000)),
                ('cargahoraria', models.IntegerField(db_column='CargaHoraria')),
                ('competencias', models.CharField(db_column='Competencias', max_length=500)),
                ('habilidades', models.CharField(db_column='Habilidades', max_length=500)),
                ('ementa', models.CharField(db_column='Ementa', max_length=500)),
                ('conteudoprogramatico', models.CharField(db_column='ConteudoProgramatico', max_length=500)),
                ('bibliografiabasica', models.CharField(db_column='BibliografiaBasica', max_length=500)),
                ('bibliografiacomplentar', models.CharField(db_column='BibliografiaComplentar', max_length=500)),
                ('percentualpratico', models.IntegerField(db_column='PercentualPratico')),
                ('percentualteorico', models.IntegerField(db_column='PercentualTeorico')),
                ('idcoordenador', models.IntegerField(db_column='IdCoordenador')),
            ],
            options={
                'db_table': 'Disciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplinaofertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcoordenador', models.IntegerField(db_column='IdCoordenador')),
                ('dtiniciomatricula', models.DateField(db_column='DtInicioMatricula')),
                ('dtfimmatricula', models.DateField(db_column='DtFimMatricula')),
                ('iddisciplina', models.IntegerField(db_column='IdDisciplina')),
                ('idcurso', models.IntegerField(db_column='IdCurso')),
                ('ano', models.IntegerField(db_column='Ano')),
                ('semestre', models.IntegerField(db_column='Semestre')),
                ('turma', models.CharField(db_column='Turma', max_length=1)),
                ('idprofessor', models.IntegerField(blank=True, db_column='IdProfessor', null=True)),
                ('metodoligia', models.CharField(blank=True, db_column='Metodoligia', max_length=500, null=True)),
                ('recursos', models.CharField(blank=True, db_column='Recursos', max_length=500, null=True)),
                ('criterioavaliacao', models.CharField(blank=True, db_column='CriterioAvaliacao', max_length=500, null=True)),
                ('planodeaulas', models.CharField(blank=True, db_column='PlanoDeAulas', max_length=500, null=True)),
            ],
            options={
                'db_table': 'DisciplinaOfertada',
                'managed': False,
            },
        ),
    ]
