from .aluno import Aluno
from .atividade import Atividade
from .atividadevinculada import Atividadevinculada
from .coordenador import Coordenador
from .curso import Curso
from .disciplina import Disciplina
from .entrega import Entrega
from .mensagem import Mensagem
from .professor import Professor
from .solicitacaomatricula import Solicitacaomatricula